# Generated by Django 4.2.1 on 2023-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_todo_post_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, db_column='END_DATE', null=True),
        ),
    ]
